### ISSUE TITLE
ID Specifications Form

### ISSUE THREAD

**Issue by AptGlobal-CIC** [sdi-connection/JS-ID-Resources#1]
### **Apt Group**

Design spec layoutand open client assessment - Examples;
[https://templates.proposify.com/proposal-template/interior-design/609282](url)
[https://www.hometrust.sg/get-recommended-interior-designers](url)

**Simsville Condo 4 pax floorplan**
![3 - 4 pax Sims condo floor-p](https://user-images.githubusercontent.com/53995407/63167941-a91e3780-c02a-11e9-8d8e-952741a09742.jpg)

[dsf.docx](https://github.com/sdi-connection/JS-ID-Resources/files/3509625/dsf.docx)

**Comment by AptGlobal-CIC** [comment]
![carpet,reception,vt,hs,wt-page-001](https://user-images.githubusercontent.com/53995407/63168507-3b730b00-c02c-11e9-8c0b-1a260cca2f26.jpg)
![Elizabeth+Burns+Design+_+Kitchen+Spec+Sheet](https://user-images.githubusercontent.com/53995407/63168509-3b730b00-c02c-11e9-8a64-d27856116294.jpg)
![example-specification-page-plumbing-1250px](https://user-images.githubusercontent.com/53995407/63168510-3b730b00-c02c-11e9-85d3-c5a6fe859b61.jpg)
![example-specification-page-tile-1250px](https://user-images.githubusercontent.com/53995407/63168511-3c0ba180-c02c-11e9-9f3e-2a2253ee8009.jpg)

**Comment by sdi-connection** [comment]
[M Sustainable Furniture.pdf](https://github.com/sdi-connection/JS-ID-Resources/files/3509748/M.Sustainable.Furniture.pdf)
